; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = esp32-s3-devkitc-1


[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board_build.embed_txtfiles =
    managed_components/espressif__esp_insights/server_certs/https_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_mqtt_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_claim_service_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_ota_server.crt
framework = espidf, arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
check_skip_packages = yes
upload_protocol = espota
upload_port = cube.local
lib_deps = 
	adafruit/Adafruit GFX Library@^1.11.3
	https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA.git#a8b172aee5710c7ab5e8c049cd001703b73f1eb9
	https://github.com/tzapu/WiFiManager.git#4131fe617d01d746677e8b909379597162c2ca58
	bblanchon/ArduinoJson @ 7.4.3
    ESP32Async/AsyncTCP @ 3.4.10
    ESP32Async/ESPAsyncWebServer @ 3.11.2
	ayushsharma82/ElegantOTA @ 3.1.7
	https://github.com/elliotmatson/ESP-DASH-Pro.git#98e43812b1a100728e59164b5e89f89a1ac71124
	https://github.com/elliotmatson/TJpg_Decoder.git#afc091a723b5885030f79b5408541a7db6f5dae6
	https://github.com/elliotmatson/spotify-api-arduino-psram.git#6a801a5af5d93dcb3078b15ffb7536d0dc2af4b5
	adafruit/Adafruit NeoPixel@^1.11.0

; V2 Hardware
[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
board_build.partitions = min_spiffs_s3.csv
board_upload.flash_size = 16MB
build_flags = 
	-DCONFIG_ARDUHAL_LOG_COLORS=1
	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1
;	-DSPIRAM_FRAMEBUFFER