name: Bug report
about: Create a report to help us improve
title: "[BUG]: "
labels: bug
assignees: ''

body:
  - type: textarea
    id: details
    attributes:
      label: Describe the bug
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      default: v0.0.0
