name: build-release

env:
  GH_TOKEN:  ${{ secrets.GH_PAT }}

on:
  workflow_dispatch:
    inputs:
      release-version:
        type: string
        description: Firmware Version
        default: 'vX.X.X'
        required: true
      release-type:
        type: choice
        description: Production or Development?
        options: 
        - 'production'
        - 'development'
        - 'build only'
        default: 'development'
  pull_request:
    
jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        pio pkg update
        # pio run -t clean
    - name: Set version var
      run: echo "PLATFORMIO_BUILD_FLAGS=-DFW_VERSION='\"${{ inputs.release-version }}\"' -DREPO_PATH='\"$GITHUB_REPOSITORY\"'" >> $GITHUB_ENV
      if: github.event_name	== 'workflow_dispatch'
    - name: Setup git for private libraries
      run: gh auth setup-git 
    - name: Run PlatformIO
      run: pio run -e esp-wrover-kit
    - name: Rename firmware
      run: cp .pio/build/esp-wrover-kit/firmware.bin esp32.bin
    - name: Cache Build
      if: github.event_name == 'workflow_dispatch'
      uses: actions/cache@v3
      with:
        path: 'esp32.bin'
        key: ${{ runner.os }}-${{ github.run_id }}

  archive:
    needs: build
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
    - name: Get Cached Build
      if: github.event_name == 'workflow_dispatch'
      uses: actions/cache@v3
      with:
        path: 'esp32.bin'
        key: ${{ runner.os }}-${{ github.run_id	 }}
    - name: Archive Build
      uses: actions/upload-artifact@v3
      with:
        name: 'build'
        path: 'esp32.bin'
        
  release:
    needs: build
    if: (github.event_name == 'workflow_dispatch' && inputs.release-type != 'build only')
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
    - name: Get Cached Build
      if: github.event_name == 'workflow_dispatch'
      uses: actions/cache@v3
      with:
        path: 'esp32.bin'
        key: ${{ runner.os }}-${{ github.run_id	 }}
    - name: Development Release
      uses: ncipollo/release-action@v1
      if: inputs.release-type == 'development'
      with:
        artifacts: '*.bin'
        generateReleaseNotes: true
        tag: ${{ inputs.release-version }}
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        makeLatest: false
    - name: Production Release
      uses: ncipollo/release-action@v1
      if: inputs.release-type == 'production'
      with:
        artifacts: '*.bin'
        generateReleaseNotes: true
        tag: ${{ inputs.release-version }}
        token: ${{ secrets.GITHUB_TOKEN }}
