name: build
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        pio pkg update
        # pio run -t clean
    - name: Set version var
      run: echo "PLATFORMIO_BUILD_FLAGS=-DFW_VERSION='\"${GITHUB_REF#refs/*/}\"' -DREPO_PATH='\"$GITHUB_REPOSITORY\"'" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/tags/v')
    - name: Run PlatformIO
      run: pio run -e esp32dev
    - name: Rename firmware
      run: cp .pio/build/esp32dev/firmware.bin esp32.bin
    - name: Release
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        artifacts: "*.bin"
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Archive Build
      uses: actions/upload-artifact@v3
      with:
        path: "*.bin"
